### ISSUE TITLE
The figures in "oneAPI GPU Optimization Guide" are broken

### ISSUE THREAD

**Issue by GHGmc2** [oneapi-src/oneAPI-samples#1807]
oneAPI GPU Optimization Guide: https://www.intel.com/content/www/us/en/docs/oneapi/optimization-guide-gpu/2023-2/intel-xe-gpu-architecture.html

**Comment by jimmytwei** [comment]
@GHGmc2 The figures seem to be working for me now. Are you still having this issue?
If not, I will close out this issue.

**Comment by GHGmc2** [comment]
> https://www.intel.com/content/www/us/en/docs/oneapi/optimization-guide-gpu/2023-2/intel-xe-gpu-architecture.html

It works now, thanks!
