### ISSUE TITLE
Request to Add a oneAPI Sample

### ISSUE THREAD

**Issue by xmnboy** [oneapi-src/oneAPI-samples#232]
# Description
Three samples to demonstrate the use of the dpct migration tool. These samples have been approved and developed in concert with Tom L., Yury P. and Swapna D.

# Dependencies
These samples have no external header or library dependencies that are necessary to be available within this repo. Obviously, they do require installation of the oneAPI dpct tool.

# Sample Folder
These three samples will be going into the `Tools/Migration` folder (the `Migration` folder is new). 

I should be issuing a pull request soon after this issue is submitted, assuming no problems. :smile:

BTW - There is no CI section, yet, in the `sample.json` because the CI system will need to be modified in order to be able to perform automated testing on these samples.

**Comment by JoeOster** [comment]
I see no issue with the proposed samples or folder location

**Comment by JoeOster** [comment]
Please submit your PR

**Comment by xmnboy** [comment]
@JoeOster -- PR is ready > https://github.com/oneapi-src/oneAPI-samples/pull/233
