### ISSUE TITLE
Replace 'dpstd' to 'oneapi::dpl' for dpc_reduce sample test

### ISSUE THREAD

**Issue by XunZhangIntel** [oneapi-src/oneAPI-samples#237]
# Summary
Newer oneDPL will get rid of dpstd namespace. So please help update dpc_reduce test to replace 'dpstd' with 'oneapi::dpl'

# Problem line
main.cpp
750:  buffer<float> calc_values(results_per_rank, num_step_per_rank);
751:  auto calc_begin2 = ~~**dpstd**~~::begin(calc_values);
752:  auto calc_end2 = ~~**dpstd**~~::end(calc_values);

**Comment by terdner** [comment]
https://github.com/oneapi-src/oneAPI-samples/pull/350 address this request. 
Txt was changed from dpstd to onedpl.  
Will reassign to bug owner so that he/she can verify fix and close bug.

**Comment by JoeOster** [comment]
This has been resolved, closing
