### ISSUE TITLE
"Simple Model" sample has a broken link

### ISSUE THREAD

**Issue by EdwardDixon** [oneapi-src/oneAPI-samples#316]
# Summary
The "simple model" [deep learning sample readme ](https://github.com/oneapi-src/oneAPI-samples/tree/master/Libraries/oneDNN/simple_model) says that the sample "includes a Jupyter Notebook", but [the link is broken](https://github.com/oneapi-src/oneAPI-samples/tree/master/Libraries/oneDNN/simple_model).

# URLs
Readme that needs updating:
https://github.com/oneapi-src/oneAPI-samples/tree/master/Libraries/oneDNN/simple_model

Non-existent notebook:
https://github.com/oneapi-src/oneAPI-samples/blob/master/Libraries/oneDNN/simple_model/simple_model.ipynb

**Comment by JoeOster** [comment]
@louie-tsai - Please update the broken linl
