### ISSUE TITLE
[SYCL][FPGA] unknown attributes warnings 

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneAPI-samples#378]
# Summary
unknown attribute 

# Version
Beta10

# Environment
Intel DevCloud

# Steps to reproduce
DPC++FPGA/Tutorials/Features/

# Observed behavior
1 warning: unknown attribute 'loop_coalesce' ignored [-Wunknown-attributes]
        [[intel::loop_coalesce(coalesce_factor)]]

2 warning: unknown attribute 'ivdep' ignored [-Wunknown-attributes]
        [[intel::ivdep(safe_len)]]
          ^

**Comment by akertesz** [comment]
These attributes (unfortunately) changed their names between beta10 and gold. 

If you sync the repo to the beta10 tag, you will get a version of code samples compatible with beta10.
The version you are using will work correctly with the imminent oneAPI gold release (2021.1).
