### ISSUE TITLE
Request to Add a oneAPI Sample OpenMP Offload Jupyter Notebook

### ISSUE THREAD

**Issue by karlqi2000** [oneapi-src/oneAPI-samples#385]
# Summary
I have some OpenMP Offload tutorial jupyter notebooks and associated code that I would like to add to oneAPI samples (currently they are on the DevCloud). This is similar to the DPC++ essential training that's currently in the samples. 
I have both C++ and Fortran jupyter notebooks. The sample should reside in DirectProgramming/C++/Jupyter   and DirectProgramming/Fortran/Jupyter

# Problem statement
Having these notebooks and code samples would help introduce users to OpenMP Offload which is supported in the oneAPI HPC toolkit.

@pmpeter1 @JoeOster  @srdontha

**Comment by JoeOster** [comment]
You are citing two domains, so long as the samples are unique to that domain, I have no real issues. Please supply the proposed folder names and paths

**Comment by pmpeter1** [comment]
No objection.
