### ISSUE TITLE
End-to-end-Workloads

### ISSUE THREAD

**Issue by cbigit** [oneapi-src/oneAPI-samples#395]
# Summary
The examples under End-to-end-Workloads appear to be empty except for Census.   Seems like the contents for Morgage, NYTaxi, and Plastic have disappeared.

# Version
2021-1.gold

# Environment
As seen on github

# Steps to reproduce
https://github.com/oneapi-src/oneAPI-samples/tree/master/AI-and-Analytics/End-to-end-Workloads/Mortgage

# Observed behavior
empty directories: Mortgage, NYTaxi, Plastic only .gitkeep

# Expected behavior
Python examples etc

**Comment by JoeOster** [comment]
Those folders are for future use and have no content as of yet. They should have been removed for the gold drop.

**Comment by JoeOster** [comment]
PR384 will remove the folders
