### ISSUE TITLE
Request to Add a oneAPI Sample Jacobi

### ISSUE THREAD

**Issue by nsaiapova** [oneapi-src/oneAPI-samples#487]
## Summary
This is a request for a new code Sample called `Jacobi`.

## Purpose
The sample code contains several bugs, so our users can try the debugger to find and fix real bugs in this sample.

## Domain
Tools / ApplicationDebugger

## Description
This is a new sample for the Application debugger. It is more complicated than the Array transform and has several bugs introduced intentionally.
The program solves the linear equation Ax=b, where matrix A is a n x n sparse matrix with diagonals [1 1 4 1 1], vector b is set such that the solution is a [1 1 ... 1]^T. The linear system is solved via Jacobi iteration. Each Jacobi iteration submits a kernel to the device (CPU, GPU, FPGA).
@barisaktemur 
@joeOster

## Dependencies
oneAPI BaseKit: DPCPP compiler

## Proposed folder Location
Tools/ApplicationDebugger/jacobi

**Comment by JoeOster** [comment]
Presented to and approved by the samples Working group on 05/07/21
