### ISSUE TITLE
Request to Add a oneAPI Sample OpenCLInterop

### ISSUE THREAD

**Issue by karlqi2000** [oneapi-src/oneAPI-samples#495]
## Summary
This is a request for a new code Sample called `DPC++ OpenCL Interoperabilty`

## Purpose
These code sample will show how OpenCL objects and Kernels can interact with DPC++. This is useful for OpenCL programmers who wants to migrate to DPC++ in a piecemeal manner, making it easier to migrate from OpenCL.

## Domain
Direct Programming / DPC++

## Description
Two examples here, one showing DPC++ compiling and launching an OpenCL Kernel. Another showing how DPC++ can use OpenCL memory, context, platform, device, kernel objects.

## Proposed folder Location
oneAPI-samples/DirectProgramming/DPC++/OpenCLInterop

@JoeOster  @pmpeter1 @bjodom @moushumi-maria

**Comment by JoeOster** [comment]
Sample proposal ppt has been submitted to the WG, with the proposal being on 05/07/21

**Comment by JoeOster** [comment]
Approved by working group
