### ISSUE TITLE
Request to Add a oneAPI Sample oneVPL Installation and Testing

### ISSUE THREAD

**Issue by mliu2020** [oneapi-src/oneAPI-samples#620]
## Summary
This is a request for a new code Sample called `oneVPL Installation and Testing`. The goal is to add Dockerfiles enabling easy and quick install the full oneVPL component from public repo on Linux, then run a simple validation test automatically. 

## Purpose
Answer the following questions
* What specifically is this code sample trying to show?
1. Provide quick start and demonstration of different OS installation deployments. Augment article for installation guide for VPL.
2. Provide quick start and concrete configuration parameters for multiple H/W platforms (i.e. Tigerlake, Sapphire Rapids, dGFX). Expectation is hardware combinations will require substantial permutations.
3. Create quick path that does not require Base Toolkit (5GB download/25GB disk space) for VPL developers.
4. Give specific instructions that may be best left abstract (universal) in online html-based installation guide.
* Why is this important to the oneAPI ecosystem?
1. Provide a quick and easy way to enable oneVPL on Linux.
2. Following the community trend to use Docker for accurate instructions.
3. Improve the developer experience and create a efficient support channel
4. Extendable for more Linux distribution support.

## Domain
oneVPL, Docker, Linux environment

## Description
oneVPL software stack includes several components out of the standard release package, this makes installation complicated. The purpose of this sample is to use Docker file to execute the whole process of installation and validation automatically. This is critical to enable the oneVPL product to the oneAPI community and broad our support in different dimensions.

## Dependencies
Docker, oneVPL of Base Toolkit, oneVPL GPU RT from public Intel graphic repo.

## Proposed folder Location
[oneVPL installation and test with Docker](https://github.com/mattcurf/onevpl_install_test)

## Checklist
[ ] Samples Working Group Permission accepted on <Insert Date>

**Comment by JoeOster** [comment]
As the direction for this and other docker containers my be changing. I will close this  for now
