### ISSUE TITLE
IntelPyTorch_GettingStarted Typos

### ISSUE THREAD

**Issue by renejsanchez** [oneapi-src/oneAPI-samples#735]
# Summary
Typos in IntelPyTorch_GettingStarted sample, step 4:
-This is a Pytorch sample, and yet step 4 says it is a TensorFlow sample
-The directory specified is missing a '-', which raises an error

# URLs
https://github.com/oneapi-src/oneAPI-samples/blob/master/AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/README.md

# Additional details
Typos fixed to avoid errors and confusion.

**Comment by louie-tsai** [comment]
@jingxu10 
Could you take a look for the issue?

**Comment by louie-tsai** [comment]
@jimmytwei 
Could you assign the issue to aice-support?

**Comment by aice-support** [comment]
@jingxu10  fixed the issue in PR#1015
