### ISSUE TITLE
URL mis-typed in README.md file

### ISSUE THREAD

**Issue by jsrobin** [oneapi-src/oneAPI-samples#809]
# Summary
On line 52 of the README.md file, it is written:
`Samples in [Alphabetical order w/ device target](https://github.com/oneapi-src/CODESAMPLESLIST.md/)`

it should read:
`Samples in [Alphabetical order w/ device target](https://github.com/oneapi-src/oneAPI-samples/blob/master/CODESAMPLESLIST.md/)`

- A similar error is on line 53.

# URLs
Include pointers to documents that are impacted.
The url of the file is:
- https://github.com/oneapi-src/oneAPI-samples/blob/master/README.md

**Comment by krzeszew** [comment]
Issue fixed in [PR888 ](https://github.com/oneapi-src/oneAPI-samples/pull/880)
