### ISSUE TITLE
Cannot compile vector-add example using dpcpp

### ISSUE THREAD

**Issue by hecmay** [oneapi-src/oneAPI-samples#844]
# Summary
I just installed intel oneapi base tool kit on my machine. but i was not able to the vector-add example provided by intel oneapi using dpcpp compiler. got a lot of compilation errors

# Version
```shell
$ dpcpp -v
Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: $HOME/intel/oneapi/compiler/2022.0.1/linux/bin-llvm
Found candidate GCC installation: /opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9
Selected GCC installation: /opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda-10.1, version 10.1
```

# Environment
```shell
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```

# Steps to reproduce
I just created a example folder for vector-add using oneapi-cli, and then ran `make all`

# Observed behavior
Got a bunch of undefined reference errors

```shell
/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../bin/ld: /home/sx233/intel/oneapi/compiler/2022.0.1/linux/bin-llvm/../lib/libsycl.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../bin/ld: /home/sx233/intel/oneapi/compiler/2022.0.1/linux/bin-llvm/../lib/libsycl.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../bin/ld: /home/sx233/intel/oneapi/compiler/2022.0.1/linux/bin-llvm/../lib/libsycl.so: undefined reference to `std::basic_fstream<char, std::char_traits<char> >::basic_fstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../bin/ld: /home/sx233/intel/oneapi/compiler/2022.0.1/linux/bin-llvm/../lib/libsycl.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../bin/ld: /home/sx233/intel/oneapi/compiler/2022.0.1/linux/bin-llvm/../lib/libsycl.so: undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../bin/ld: /home/sx233/intel/oneapi/compiler/2022.0.1/linux/bin-llvm/../lib/libsycl.so: undefined reference to `std::_V2::error_category::_M_message[abi:cxx11](int) const@GLIBCXX_3.4.21'/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../bin/ld: /home/sx233/intel/oneapi/compiler/2022.0.1/linux/bin-llvm/../lib/libsycl.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
```

I have checked the libstdc++ linked to this SO lib by running ldd, and i was able find `GLIBCXX_3.4.21`  strings inside. I also tried to disabled the cxx11 ABI by adding `-D_GLIBCXX_USE_CXX11_ABI=0` flag when compiling it, but it does not really help

# Expected behavior
To compile

**Comment by junlizha** [comment]
For the libsycl in oneAPI is compiled by enabling _GLIBCXX_USE_CXX11_ABI, the sycl example code should follow the same rule. But on CentOS7/RHEL7 the  _GLIBCXX_USE_CXX11 has set to disable by default. You can find the reason from this page: https://bugzilla.redhat.com/show_bug.cgi?id=1546704. 
We can force enable this feature by doing some changes to devtoolset-9 like:
sed -i 's:# define _GLIBCXX_USE_DUAL_ABI 0:# define _GLIBCXX_USE_DUAL_ABI 1:g' \
  /opt/rh/devtoolset-9/root/usr/include/c++/9/x86_64-redhat-linux/bits/c++config.h
The libstdc++ shipped with CentOS7/RHEL7 is not compatible with libsycl, so you have to use the libstdc++ shipped with OneAPI to succeed the system wide libstdc++ like:
LDFLAGS="-Wl,-rpath,/opt/intel/oneapi/clck/latest/lib_common/intel64 -Wl,--start-group /opt/intel/oneapi/clck/latest/lib_common/intel64/libstdc++.so.6.0.28 -Wl,--end-group"
Finally, compile the sycl codes with _GLIBCXX_USE_CXX11_ABI enabled like:
CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=1"
dpcpp $CXXFLAGS $LDFLAGS foo.cpp -o foo
At last, you will got a runnable binary. Have fun!
