### ISSUE TITLE
Is multi-gpu supported in oneapi?

### ISSUE THREAD

**Issue by kakulo** [oneapi-src/oneAPI-samples#937]
I am running a few CNN/DNN examples within oneDNN, but it always run on a single Nvidia GPU. Is there a way to run on multiple Nivida GPUs? Is it currently supported or do I miss something? Thanks!

**Comment by aice-support** [comment]
oneDNN supports computation & memory primitives.
For communication support such as all reduce among multiple devices, oneCCL supports those communications operations. 
However, you might need to use NCCL for those communication operations on NVidia GPUs.

**Comment by yehudaorel** [comment]
> oneDNN supports computation & memory primitives. For communication support such as all reduce among multiple devices, oneCCL supports those communications operations. However, you might need to use NCCL for those communication operations on NVidia GPUs.

@kakulo 
Was that able to answer your question?

**Comment by aice-support** [comment]
@kakulo 
Hope our response solves your problem.
We will close the issue for now, and feel free to reopen the issue if you still have problem.
